config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions'
}

  root to: "home#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update]
  resources :auction_lots, only: [:index,:show, :new, :create, :edit, :update] do
    resources :product_items, only: [:new, :create, :destroy]
    resources :bids, only: [:create]
    post 'active', on: :member
    post 'closed', on: :member
    post 'cancel', on: :member
    get 'results', on: :collection
    get 'customer_results', on: :collection
    get 'search', on: :collection
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :blockeds, only: [:index, :new, :create, :destroy]
end

app/models/auction_lot.rb
class AuctionLot < ApplicationRecord
  has_many :product_items, dependent: :destroy
  has_many :products, through: :product_items
  has_many :auction_lots, through: :product_items
  has_many :favorites
  has_many :users, through: :favorites
  has_many :bids
  accepts_nested_attributes_for :product_items

  enum status: { draft: 0, active: 1, started: 2, canceled: 3, closed: 5}
  
  validates :code, :start_date, :end_date, :minimum_value, :diff_value, :admin_record, presence: true
  validates :code, uniqueness: true
  validate :code_valid?
  validate :valid_start_date?


  def code_valid?
    unless self.code.present? && self.code.match?(/^(?=.*[A-Za-z]{3})(?=.*\d{6})[A-Za-z\d]{9}$/)
      self.errors.add(:code, "Inválido")
    end
  end

  def valid_start_date?
    if self.start_date.present? && self.start_date > self.end_date
      self.errors.add(:start_date, "não pode ser menor que a data final do lote")
    end
  end
end

app/controllers/auction_lots_controller.rb
class AuctionLotsController < ApplicationController

  before_action :check_admin, only: [:edit, :update, :new, :create, :index]

  def index
    @auction_lots = AuctionLot.draft
  end

  def show
    @auction_lot = AuctionLot.find(params[:id])
    @bid = Bid.new
    @amount = @auction_lot.bids.last
  end

  def new
    @auction_lot = AuctionLot.new
    @auction_lot.product_items.build
    @products = Product.all
    @product = Product.new
  end

  def create
    auction_lot_params = params.require(:auction_lot).permit(:end_date, :minimum_value, :diff_value,
                                                             :code, :start_date)
    @auction_lot = AuctionLot.new(auction_lot_params)
    @auction_lot.admin_record = current_user.email

    if @auction_lot.save
      redirect_to @auction_lot, notice: "Cadastro do lote de leilão efetuado com sucesso."
    else
      @products = Product.all
      flash.now[:alert] = "Falha ao criar o lote de leilão"
      render "new"
    end
  end

  def edit
    @products = Product.all
    @auction_lot = AuctionLot.find(params[:id])
  end

  def update
    @auction_lot = AuctionLot.find(params[:id])
    auction_lot_params = params.require(:auction_lot).permit(:start_date, :end_date, :minimum_value,
                                        :diff_value)

    if @auction_lot.update(auction_lot_params)
      redirect_to auction_lot_path(params[:id]), notice: "Lote de leilão atualizado com sucesso."
    else
      @products = Product.all
      flash[:alert] = "Não foi possivel atualizar o lote."
      render "edit"
    end
  end

  def active
    @auction_lot = AuctionLot.find(params[:id])
    if @auction_lot.admin_record == current_user.email
      redirect_to @auction_lot, alert: "Voce não pode aprovar esse lote"
    elsif @auction_lot.product_items.any?
      @auction_lot.active!
      @auction_lot.admin_approve = current_user.email
      @auction_lot.save
      redirect_to @auction_lot
    else
      redirect_to @auction_lot, alert: "O lote não pode ser aprovado sem ter ao menos um produto vinculados."
    end
  end

  def results
    overdue_lot_query
  end

  def closed
    @auction_lot = AuctionLot.find(params[:id])
    @auction_lot.closed!
    redirect_to results_auction_lots_path, notice: "Lote de leilão finalizado com sucesso!"
  end

  def cancel
    @auction_lot = AuctionLot.find(params[:id])
    
    @auction_lot.product_items.each do |prd_itm|
      product = Product.find(prd_itm.product_id)
      product.active!
    end
    
    if @auction_lot.canceled!
      redirect_to results_auction_lots_path, notice: "Lote de leilão cancelado com sucesso!"
    end
  end

  def customer_results
    if !current_user.present? 
      redirect_to new_user_session_path
    else
    current_user_id = current_user.id
    @auction_lots = AuctionLot.joins(:bids).where("auction_lots.end_date < ? AND auction_lots.status = 5 AND bids.user_id = ?", Date.today, current_user_id)
    end
  end

  def search
    @key = params["query"]
    @auction_lots = AuctionLot.joins(:products).where("products.name LIKE ? OR auction_lots.code LIKE ? ", "%#{@key}%", "%#{@key}%")
  end

  private

  def check_admin
    unless current_user.present? && current_user.admin?
      flash[:alert] = "Apenas usuarios admin tem acesso a essa ação"
      return redirect_to root_path
    end
  end

  def overdue_lot_query
    @auction_lots = AuctionLot.where('end_date <= ? AND status = ?', Date.today, 1)
  end
end

app/views/auction_lots/customer_results.html.erb
<div class="container">
  <h2 class="text-center">Lotes que voce ganhou!</h2>
  
  <%= link_to 'Voltar', root_path, class:"btn btn-secondary mb-4"%>
  
  <div class="row">
    <% if @auction_lots.any? %>
      <% @auction_lots.each do |lot| %>
        <div class="col-md-6 mb-4">
          <div class="card">
            <div class="card-body">
              <% bid = lot.bids.last %>
              <dl class="row mb-0">
                <dt class="col-sm-6">Código do lote:</dt>
                <dd class="col-sm-6"><%= link_to lot.code, lot%></dd>
                <dt class="col-sm-6">Encerrado em:</dt>
                <dd class="col-sm-6"><%= lot.end_date.strftime("%d/%m/%Y") %></dd>
                <dt class="col-sm-6">Valor do lance:</dt>
                <dd class="col-sm-6"><%= number_to_currency bid.amount %></dd>
                <dt class="col-sm-6">Status:</dt>
                <dd class="col-sm-6"><%= I18n.t(lot.status) %></dd>
              </dl>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>Você ainda não ganhou nenhum lote</p>
    <% end %>
  </div>
</div>

app/views/auction_lots/edit.html.erb
<div class="container">
  <h3>Editando o lote "<%= @auction_lot.code %>" para leilão</h3>

  <%= link_to 'Voltar', auction_lots_path, class: "btn btn-secondary mr-2 mt-3 mr-auto mb-4" %>


  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <% if @auction_lot.errors.any? %>
    <div class="alert alert-danger">
      <p>Verifique os erros abaixo:</p>
      <ul>
        <% @auction_lot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @auction_lot, class: 'form') do |f| %>
    <div class="row">
      <div class="col-sm-5">
        <div class="form-group">
          <%= f.label :start_date, 'Data início do lote' %>
          <%= f.date_field :start_date, class: 'form-control', size: 10, style: "width: 150px;" %>
        </div>

        <div class="form-group">
          <%= f.label :end_date, 'Data final do lote' %>
          <%= f.date_field :end_date, class: 'form-control', size: 10, style: "width: 150px;" %>
        </div>
      </div>

      <div class="col-sm-5" style="margin-top: 25px;">
        <div class="form-group">
          <%= f.label :minimum_value, 'Valor mínimo' %>
          <%= f.number_field :minimum_value, class: 'form-control', size: 10, style: "width: 150px;" %>
        </div>

        <div class="form-group">
          <%= f.label :diff_value, 'Valor diferença de lance' %>
          <%= f.number_field :diff_value, class: 'form-control', size: 10, style: "width: 150px;" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Enviar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/auction_lots/index.html.erb
<h1 class="text-center">Lotes para Leilão</h1>

  <div class="mb-4">
    <div class="text-end mb-3">
      <div class="d-flex justify-content-between">
        <%= link_to 'Voltar', root_path, class: "btn btn-secondary ms-5" %>
        <%= link_to '+ Novo Lote de Leilão', new_auction_lot_path, class: "btn btn-primary me-5" %>
      </div>
    </div>
  </div>

  <div class="row">
    <% @auction_lots.each do |lot| %>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-body">
              <h5 class="card-title">Código: <%= lot.code%></h5>
              <dl>
                <dt>Inicio: </dt>
                <dd><%= I18n.localize lot.start_date%></dd>
                <dt>Final: </dt>
                <dd><%= I18n.localize lot.end_date%></dd>
              </dl>
              <%= link_to 'Ver Detalhes', lot, class: "btn btn-primary", id: dom_id(lot) %>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/auction_lots/new.html.erb
<div class="container mt-4">
  <h3>Criando lote para leilão</h3>

  <%= link_to 'Voltar', auction_lots_path, class: "btn btn-secondary mr-2 mt-3 mr-auto mb-4" %>


  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <% if(@auction_lot.errors.any?) %>
    <div class="alert alert-danger" role="alert">
      <p> Verifique os erros abaixo: </p>
      <ul>
        <% @auction_lot.errors.full_messages.each do |msg| %>
          <li><%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @auction_lot, class: "row g-3") do |f| %>
    <div class="col-md-6 mt-3">
      <%= f.label :code, class: "form-label" %>
      <%= f.text_field :code, class: "form-control", size: 10, style: "width: 190px;", placeholder: "3 letras e 6 caracteres" %>
    </div>
    <div class="col-md-6 mt-3">
      <%= f.label :minimum_value, class: "form-label" %>
      <%= f.number_field :minimum_value, class: "form-control", size: 10, style: "width: 150px;" %>
    </div>
    <div class="col-md-6 mt-3">
      <%= f.label :start_date, class: "form-label" %>
      <%= f.date_field :start_date, class: "form-control", size: 10, style: "width: 150px;" %>
    </div>
    <div class="col-md-6 mt-3">
      <%= f.label :diff_value, class: "form-label" %>
      <%= f.number_field :diff_value, class: "form-control", size: 10, style: "width: 150px;" %>
    </div>
    <div class="col-md-6 mt-3">
      <%= f.label :end_date, class: "form-label" %>
      <%= f.date_field :end_date, class: "form-control", size: 10, style: "width: 150px;" %>
    </div>


    <div class="col-12 mt-3">
      <%= f.submit 'Enviar', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/auction_lots/results.html.erb
<div class="container">
  <h3 class="text-center">Validação de resultados dos leilões</h3>
  
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
  
    <%= link_to 'Voltar', root_path, class: "btn btn-secondary mb-5" %>
  
  <div class="row">
    <% @auction_lots.each do |lot| %>
      <div class="col-md-6 mb-4">
        <div class="card">
          <div class="card-body">
            <% if lot.bids.any? %>
              <% bid = lot.bids.last %>
              <h5 class="card-title"><%= link_to lot.code, lot %></h5>
              <dl class="row mb-0">
                <dt class="col-sm-6">Encerrado em:</dt>
                <dd class="col-sm-6"><%= lot.end_date.strftime("%d/%m/%Y") %></dd>
                <dt class="col-sm-6">Valor inicial:</dt>
                <dd class="col-sm-6"><%= number_to_currency lot.minimum_value %></dd>
                <dt class="col-sm-6">Ultimo lance:</dt>
                <dd class="col-sm-6"><%= number_to_currency bid.amount %></dd>
                <dt class="col-sm-6">Ganhador:</dt>
                <dd class="col-sm-6"><%= bid.user.name %></dd>
              </dl>
              <%= button_to 'Finalizar', closed_auction_lot_path(lot.id), id: dom_id(lot), class: "btn btn-primary mt-3" %>
            <% else %>
              <h5 class="card-title"><%= link_to lot.code, lot %></h5>
              <dl class="row mb-0">
                <dt class="col-sm-6">Encerrado em:</dt>
                <dd class="col-sm-6"><%= lot.end_date.strftime("%d/%m/%Y") %></dd>
                <dt class="col-sm-6">Valor inicial:</dt>
                <dd class="col-sm-6"><%= number_to_currency lot.minimum_value %></dd>
                <dt class="col-sm-6">Nenhum lance registrado.</dt>
              </dl>
              <%= button_to 'Cancelar', cancel_auction_lot_path(lot.id), id: dom_id(lot), class: "btn btn-danger mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/auction_lots/search.html.erb
<div class="container">
  <div class="card mt-4">
    <div class="card-header">
      <h3 class="card-title">Resultado da Busca por: <%= @key %></h3>
    </div>
    <p><%= @auction_lots.size %> <%= AuctionLot.model_name.human(count: @auction_lots.size).downcase%> <%= I18n.t(:found, count: @auction_lots.size)%> </p>
    <div class="card-body">
      <% if @auction_lots.any? %>
        <div>
          <% @auction_lots.each do |lot| %>
            <dl>
              <dt>Código do lote:</dt>
              <dd><%= link_to lot.code, lot%></dd>
            </dl>
          <% end %>
        </div>
      <% else %>
         <p>Nenhum resultado foi encontrado.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/auction_lots/show.html.erb
<div class="container mt-4">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>
  <%= link_to 'Voltar', root_path, class: "btn btn-secondary mr-2 mt-3 mr-auto mb-4" %>
  <div class="btn-group" role="group" aria-label="Ações">
  <% if current_user.present? && current_user.customer?%>
      <%= form_with url: favorites_path, method: :post do |form| %>
        <%= form.hidden_field :auction_lot_id, value: @auction_lot.id %>
        <%= form.submit "Favoritar", class: "btn btn-info mt-3 mb-4 ms-2" %>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12">
      <h3>Código do Leilão: <%= @auction_lot.code %></h3>
    </div>
  </div>

  <div class="row no-gutters">
    <div class="col-md-6">
      <dl class="row">
        <dt class="col-sm-3">Data de início:</dt>
        <dd class="col-sm-9"><%= I18n.localize(@auction_lot.start_date) %></dd>
        <dt class="col-sm-3">Data final do lote:</dt>
        <dd class="col-sm-9"><%= I18n.localize(@auction_lot.end_date) %></dd>
        <dt class="col-sm-3">Valor mínimo:</dt>
        <dd class="col-sm-9"><%= number_to_currency(@auction_lot.minimum_value) %></dd>
        <dt class="col-sm-3">Valor diferença:</dt>
        <dd class="col-sm-9"><%= number_to_currency(@auction_lot.diff_value) %></dd>
        <dt class="col-sm-3">Responsável:</dt>
        <dd class="col-sm-9"><%= @auction_lot.admin_record %></dd>
        <dt class="col-sm-3">Aprovado por:</dt>
        <dd class="col-sm-9"><%= @auction_lot.admin_approve %></dd>
        <dt class="col-sm-3">Status:</dt>
        <dd class="col-sm-9"><%= I18n.t(@auction_lot.status) %></dd>
        <% if @auction_lot.active? %>
          <dt class="col-sm-3">Último lance:</dt>
          <% unless @amount.nil? %>
            <dd class="col-sm-9"><%= number_to_currency(@amount.amount) %></dd>
          <% else %>
            <dd class="col-sm-9">Nenhum lance foi dado até o momento</dd>
          <% end %>
        <% end %>
      </dl>

      <% if @auction_lot.active? %>
        <%= form_with(model: [@auction_lot, @bid], local: true) do |f| %>
          <div class="form-group">
            <%= f.label :amount, "Valor do lance" %>
            <%= f.number_field :amount, class: "form-control", size: 10, style: "width: 150px;" %>
          </div>
          <%= f.submit "Enviar lance", class: "btn btn-primary mt-2" %>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-6">
      <% @auction_lot.product_items.each do |item| %>
        <div class="col-md-6 col-lg-4 mb-3">
          <div class="card">
            <%= image_tag(item.product.photo, class: "card-img-top", alt: "product image", style: "height: 100%; width: 100%; object-fit: cover;") %>
            <div class="card-body">
              <% if current_user.present? && current_user.admin? && @auction_lot.draft?%>
                <%= button_to "Remover", auction_lot_product_item_path(auction_lot_id: @auction_lot, id: item), method: :delete, class: "btn btn-danger", id: dom_id(item) %>
              <% end %>  
              <h5 class="card-title"><%= item.product.name %></h5>
              <p class="card-text"><%= item.product.description %></p>
              <p class="card-text">Categoria: <%= item.product.category %></p>
              <p class="card-text">Dimensões: <%= dimension(item.product.height, item.product.width, item.product.depth) %></p>
              <p class="card-text">Peso: <%= item.product.weight %>g</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if @auction_lot.draft? %>
    <% if current_user.present? && current_user.admin? %>
      <div class="row mt-3">
        <div class="col-md-12 d-flex justify-content-between">
          <div class="btn-group">
            <%= link_to 'Editar', edit_auction_lot_path, class: "btn btn-primary mr-2" %>
            <%= link_to 'Adicionar Items', new_auction_lot_product_item_path(auction_lot_id: @auction_lot.id), class: "btn btn-warning mr-2 ms-2" %>
            <%= button_to 'Aprovar', active_auction_lot_path(@auction_lot.id), class: "btn btn-success mr-2 ms-2" %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>