config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions'
}

  root to: "home#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update]
  resources :auction_lots, only: [:index,:show, :new, :create, :edit, :update] do
    resources :product_items, only: [:new, :create, :destroy]
    resources :bids, only: [:create]
    post 'active', on: :member
    post 'closed', on: :member
    post 'cancel', on: :member
    get 'results', on: :collection
    get 'customer_results', on: :collection
    get 'search', on: :collection
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :blockeds, only: [:index, :new, :create, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :auction_lot
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    if !current_user.present? 
      redirect_to new_user_session_path
    else
    @favorites = current_user.favorites.includes(auction_lot: :products)
    end
  end

  def create
    @auction_lot = AuctionLot.find(params[:auction_lot_id])
    user = current_user 
    @favorite =  Favorite.new(user: user, auction_lot: @auction_lot)
    if @favorite.save
      redirect_to favorites_path
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to @favorite, notice: "O lote foi removido dos favoritos."
  end
end

app/views/favorites/index.html.erb
<div class="container">
<h2 class="text-center">Seus lotes favoritos</h2>

  <%= link_to 'Voltar', root_path, class:"btn btn-secondary mb-4"%>

  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

<% if @favorites.any? %>
  <div class="row">
<% @favorites.each do |favorite| %>
  <% lot = favorite.auction_lot %>
  <div class="col-md-4">
    <div class="card mb-4">
      <div class="card-body">
        <h5 class="card-title">Código: <%= lot.code %></h5>
        <dl>
          <dt>Categoria:</dt>
          <% lot.products.each do |product| %>
            <dd><%= product.category %></dd>
          <% end %>
          <dt>Início:</dt>
          <dd><%= I18n.localize(lot.start_date) %></dd>
          <dt>Final:</dt>
          <dd><%= I18n.localize(lot.end_date) %></dd>
        </dl>
        <%= link_to 'Ver Detalhes', lot, class: "btn btn-primary", id: dom_id(lot) %>
        <div class="btn-group" role="group" aria-label="Ações">
          <%= form_tag(favorite_path(favorite), method: :delete) do %>
            <%= submit_tag 'Remover', class: 'btn btn-danger', id: dom_id(favorite) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
  </div>
<% else %>
  <p>Você ainda não adicionou nenhum lote aos seus favoritos.</p>
<% end %>
</div>