config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions'
}

  root to: "home#index"

  resources :products, only: [:index, :new, :create, :show, :edit, :update]
  resources :auction_lots, only: [:index,:show, :new, :create, :edit, :update] do
    resources :product_items, only: [:new, :create, :destroy]
    resources :bids, only: [:create]
    post 'active', on: :member
    post 'closed', on: :member
    post 'cancel', on: :member
    get 'results', on: :collection
    get 'customer_results', on: :collection
    get 'search', on: :collection
  end
  resources :favorites, only: [:index, :create, :destroy]
  resources :blockeds, only: [:index, :new, :create, :destroy]
end

app/views/layouts/navs/_nav_admin.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Site do Leilão', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-nowrap">
        <li class="nav-item">
          <%= link_to 'Produtos', products_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lote de leilão', auction_lots_path, class: 'nav-link text-truncate' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Resultados', results_auction_lots_path, class: 'nav-link text-truncate' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Restrições', blockeds_path, class: 'nav-link text-truncate' %>
        </li>
      </ul>
      <%= form_with(url: search_auction_lots_path, method: :get) do |f|%>
        <%= f.text_field :query, placeholder: 'Busque um produto' %>
        <%= f.submit 'Buscar' %>
      <% end %>
      <% if user_signed_in? %>
        <span class="navbar-text mx-3">Olá <%= current_user.name %></span>
        <%= button_to 'Sair', destroy_user_session_path, method: :delete, class:"btn btn-light"%>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path, class: 'btn btn-outline-primary me-3' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/navs/_nav_customer.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Site do Leilão', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-nowrap">
        <li class="nav-item">
          <%= link_to 'Resultados', customer_results_auction_lots_path, class: 'nav-link text-truncate' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favoritos', favorites_path, class: 'nav-link text-truncate' %>
        </li>
      </ul>
      <%= form_with(url: search_auction_lots_path, method: :get) do |f|%>
        <%= f.text_field :query, placeholder: 'Busque um produto' %>
        <%= f.submit 'Buscar' %>
      <% end %>
      <% if user_signed_in? %>
        <span class="navbar-text mx-3">Olá <%= current_user.name %></span>
        <%= button_to 'Sair', destroy_user_session_path, method: :delete, class:"btn btn-light"%>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path, class: 'btn btn-outline-primary ms-3' %>
      <% end %>
    </div>
  </div>
</nav>